version: '3'

services:
  create-picture:
    build:
      context: services/backend-for-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Expose the port your Express app is listening on

  nginx:
    build:
      context: services/web
      dockerfile: Dockerfile
    ports:
      - "8080:80" # Expose port 8080 for Nginx
    depends_on:
      - create-picture
